// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.mjs";

Test.test("Add", (function (param) {
        return Test.assertion("One equals one", "Int equals", (function (a, b) {
                      return a === b;
                    }), 1, 1);
      }));

export {
  
}
/*  Not a pure module */
