// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Chai from "chai";
import * as React from "react";
import * as React$1 from "@testing-library/react";
import * as App$AppTemplateReasonReact from "../App.bs.js";

it("renders learn react link", (function () {
        React$1.render(React.createElement(App$AppTemplateReasonReact.make, {}));
        var actual = React$1.getNodeText(React$1.screen.getByText("Learn React"));
        Chai.assert.equal(actual, "Learn React");
        
      }));

export {
  
}
/*  Not a pure module */
