// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Task_088$RescriptPlayground from "./Task_088.mjs";

console.log(Belt_List.toArray(Task_088$RescriptPlayground.razmen(11, Task_088$RescriptPlayground.cash1)));

console.log(Belt_List.toArray(Task_088$RescriptPlayground.razmen(11, Task_088$RescriptPlayground.coins1)));

console.log(Task_088$RescriptPlayground.main([
          0.10,
          0.01
        ]));

export {
  
}
/*  Not a pure module */
