// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Task_088$RescriptPlayground from "./Task_088.mjs";

console.log(Belt_List.toArray(Task_088$RescriptPlayground.razmen(0.5700000000000003, Task_088$RescriptPlayground.coins1)));

console.log(Task_088$RescriptPlayground.main([
          0.01,
          0.01,
          0.05,
          0.50,
          0.50,
          0.50,
          1,
          1,
          1,
          1,
          5,
          5,
          5,
          10,
          10,
          10,
          10
        ]));

export {
  
}
/*  Not a pure module */
