// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LC_number_of_dice_rolls_with_target_sum$RescriptPlayground from "./LC_number_of_dice_rolls_with_target_sum.mjs";

console.log(LC_number_of_dice_rolls_with_target_sum$RescriptPlayground.numRollsToTarget(1, 6, 3));

console.log(LC_number_of_dice_rolls_with_target_sum$RescriptPlayground.numRollsToTarget(2, 6, 7));

console.log(LC_number_of_dice_rolls_with_target_sum$RescriptPlayground.numRollsToTarget(4, 3, 7));

console.log(LC_number_of_dice_rolls_with_target_sum$RescriptPlayground.numRollsToTarget(30, 3, 50));

export {
  
}
/*  Not a pure module */
