// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function stockList(listOfArt, listOfCat) {
  if (!(listOfArt.length !== 0 && listOfCat.length !== 0)) {
    return "";
  }
  var listOfArt$1 = Belt_Array.map(listOfArt, (function (a) {
          var match = a.split(" ");
          if (match.length !== 2) {
            return Pervasives.failwith("");
          }
          var a$1 = match[0];
          var b = match[1];
          return [
                  a$1[0],
                  Belt_Option.getExn(Belt_Int.fromString(b))
                ];
        }));
  var cats = Belt_Array.map(listOfCat, (function (c) {
          var match = Belt_Array.unzip(Belt_Array.keep(listOfArt$1, (function (param) {
                      return param[0] === c;
                    })));
          var i = Belt_Array.reduce(match[1], 0, (function (prim0, prim1) {
                  return prim0 + prim1 | 0;
                }));
          return "(" + (c + (" : " + (String(i) + ")")));
        }));
  return cats.join(" - ");
}

export {
  stockList ,
  
}
/* No side effect */
