// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";

function validParentheses_aux(_parens_list, _acc) {
  while(true) {
    var acc = _acc;
    var parens_list = _parens_list;
    if (acc < 0) {
      return -1;
    }
    if (!parens_list) {
      return acc;
    }
    switch (parens_list.hd) {
      case "(" :
          _acc = acc + 1 | 0;
          _parens_list = parens_list.tl;
          continue ;
      case ")" :
          _acc = acc - 1 | 0;
          _parens_list = parens_list.tl;
          continue ;
      default:
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "Kata_52774a314c2333f0a7000688.ml",
                8,
                11
              ],
              Error: new Error()
            };
    }
  };
}

function validParentheses(parens) {
  var match = validParentheses_aux(Belt_List.fromArray(parens.split("")), 0);
  return match === 0;
}

export {
  validParentheses_aux ,
  validParentheses ,
  
}
/* No side effect */
