// Generated by ReScript, PLEASE EDIT WITH CARE


function modulo(n) {
  return n % 1000000007;
}

function factorial(n) {
  if (n === 0) {
    return 1;
  } else {
    return Math.imul(n, factorial(n - 1 | 0) % 1000000007) % 1000000007;
  }
}

function numRollsToTarget(n, k, target) {
  var $$enum = function (depth, current, sum) {
    if (depth === n) {
      if (sum === target) {
        return 1;
      } else {
        return 0;
      }
    }
    var s = 0;
    for(var i = current; i <= k; ++i){
      s = (s % 1000000007 + $$enum(depth + 1 | 0, i, sum + i | 0) % 1000000007 | 0) % 1000000007;
    }
    return s;
  };
  return Math.imul($$enum(0, 1, 0) % 1000000007, factorial(n) % 1000000007) % 1000000007;
}

export {
  modulo ,
  factorial ,
  numRollsToTarget ,
  
}
/* No side effect */
