// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Float from "rescript/lib/es6/belt_Float.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function main(a, b1, b2, x) {
  return Belt_Option.getExn(Belt_Float.fromString((a / (b1 + b2) * x * 1000).toFixed(2)));
}

export {
  main ,
  
}
/* No side effect */
