// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function main(numbers_list1, numbers_list2) {
  return Belt_Array.map(Belt_Array.zip(numbers_list1, numbers_list2), (function (param) {
                return Caml_obj.caml_min(param[0], param[1]);
              }));
}

export {
  main ,
  
}
/* No side effect */
