// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function main(n, k) {
  return [
          Caml_int32.div(k, n),
          Caml_int32.mod_(k, n)
        ];
}

export {
  main ,
  
}
/* No side effect */
