// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function razmen(money, coins) {
  var a = Belt_Array.reduce(coins, undefined, (function (acc, el) {
          if (acc !== undefined) {
            return acc;
          } else if (money >= el) {
            return el;
          } else {
            return ;
          }
        }));
  if (a !== undefined) {
    return {
            hd: a,
            tl: razmen(money - a, coins)
          };
  } else {
    return /* [] */0;
  }
}

var coins1 = [
    0.01,
    0.05,
    0.10,
    0.25,
    0.50,
    1.00,
    5.00,
    10.00
  ].reverse();

var cash1 = [
    10,
    50,
    100,
    500,
    1000
  ].reverse();

function main(coins) {
  var m = Belt_Array.reduce(coins, 0, (function (a, b) {
          return a + b;
        }));
  var ca = razmen(m, cash1);
  var mca = Belt_List.reduce(ca, 0, (function (a, b) {
          return a + b;
        }));
  var co = razmen(m - mca, coins1);
  return [
          Belt_List.toArray(ca),
          Belt_List.toArray(co)
        ];
}

export {
  razmen ,
  coins1 ,
  cash1 ,
  main ,
  
}
/* coins1 Not a pure module */
