// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function razmen(money, coins) {
  var a = Belt_Array.reduceU(coins, undefined, (function (acc, el) {
          if (acc !== undefined) {
            return acc;
          } else if (money >= el) {
            return el;
          } else {
            return ;
          }
        }));
  if (a !== undefined) {
    return {
            hd: a,
            tl: razmen(money - a | 0, coins)
          };
  } else {
    return /* [] */0;
  }
}

var coins1 = [
    1,
    5,
    10,
    25,
    50,
    100,
    500,
    1000
  ].reverse();

var cash1 = [
    1000,
    5000,
    10000,
    50000,
    100000
  ].reverse();

function toc(a) {
  return a / 100;
}

function main(coins2) {
  var coins = Belt_Array.mapU(coins2, (function (a) {
          return a * 100 | 0;
        }));
  var m = Belt_Array.reduceU(coins, 0, (function (a, b) {
          return a + b | 0;
        }));
  var ca = razmen(m, cash1);
  var mca = Belt_List.reduceU(ca, 0, (function (a, b) {
          return a + b | 0;
        }));
  var co = razmen(m - mca | 0, coins1);
  return [
          Belt_List.toArray(Belt_List.mapU(ca, toc)),
          Belt_List.toArray(Belt_List.mapU(co, toc))
        ];
}

export {
  razmen ,
  coins1 ,
  cash1 ,
  toc ,
  main ,
  
}
/* coins1 Not a pure module */
