// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Float from "rescript/lib/es6/belt_Float.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function main(figure, sides) {
  var tmp;
  if (figure === "triangle") {
    if (sides.length !== 3) {
      tmp = 0;
    } else {
      var a = sides[0];
      var b = sides[1];
      var c = sides[2];
      var p = (a + b + c) / 2;
      tmp = Math.sqrt(p * (p - a) * (p - b) * (p - c));
    }
  } else if (figure === "rectangle") {
    if (sides.length !== 2) {
      tmp = 0;
    } else {
      var a$1 = sides[0];
      var b$1 = sides[1];
      tmp = a$1 * b$1;
    }
  } else if (sides.length !== 1) {
    tmp = 0;
  } else {
    var r = sides[0];
    tmp = Math.PI * Math.pow(r, 2);
  }
  return Belt_Option.getWithDefault(Belt_Float.fromString(tmp.toFixed(2)), 0);
}

export {
  main ,
  
}
/* No side effect */
